options:
  lineNumbers: true
  spellcheck: false
  imagePath: /images/2021.05/
  askImageFilename: true
  overwriteImages: true
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: false
