# Site
name: "mcat"
title: "小吴同学的科学空间之旅"
description: "一起探讨人生百味"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'wj-mcat-blog'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  wj-Mcat:
    name: 吴京京
    display_name: 小吴同学
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wjmcater@gmail.com
    web: https://wj-mcat.github.io/
    twitter: https://twitter.com/wjmcat
    description: "北京邮电大学人工智能学院研究生、Chatbot技术爱好者、热爱开源和分享"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
